CREATE TABLE
    product_type (PRODUCT_TYPE_CD VARCHAR(255) UNIQUE PRIMARY KEY , NAME VARCHAR(50));

CREATE TABLE
    product (
        PRODUCT_CD VARCHAR(10) UNIQUE PRIMARY KEY,
        DATE_OFFERED DATE,
        DATE_RETIRED DATE,
        NAME VARCHAR(50),
        PRODUCT_TYPE_CD VARCHAR(255) REFERENCES product_type (PRODUCT_TYPE_CD)
    );

CREATE TABLE
    branch (
        BRANCH_ID INT UNIQUE PRIMARY KEY,
        ADDRESS VARCHAR(30),
        CITY VARCHAR(20),
        NAME VARCHAR(20),
        STATE VARCHAR(10),
        ZIP_CODE VARCHAR(12)
    );

CREATE TABLE
    acc_transaction (
        TXN_ID BIGINT UNIQUE PRIMARY KEY,
        AMOUNT FLOAT,
        FUNDS_AVAIL_DATE TIMESTAMP,
        TXN_DATE TIMESTAMP,
        TXN_TYPE_CD VARCHAR(10),
        ACCOUNT_ID INT REFERENCES account (ACCOUNT_ID),
        EXECUTION_BRANCH_ID INT REFERENCES branch (BRANCH_ID),
        TELLER_EMP_ID INT REFERENCES employee (EMP_ID)
    );

CREATE TABLE
    employee (
        EMP_ID INT UNIQUE PRIMARY KEY,
        FIRST_NAME VARCHAR(20),
        LAST_NAME VARCHAR(20),
        START_DATE DATE,
        END_DATE DATE,
        TITLE VARCHAR(20),
        ASSIGNED_BRANCH_ID INT REFERENCES branch (BRANCH_ID),
        DEPT_ID INT REFERENCES department (DEPT_ID),
        SUPERIOR_EMP_ID INT REFERENCES employee (EMP_ID)
    );

CREATE TABLE
    department (DEPT_ID INT UNIQUE PRIMARY KEY, NAME VARCHAR(20));

CREATE TABLE
    account (
        ACCOUNT_ID INT UNIQUE PRIMARY KEY,
        AVAIL_BALANCE FLOAT,
        PENDING_BALANCE FLOAT,
        CLOSE_DATE DATE,
        OPEN_DATE DATE,
        LAST_ACTIVITY_DATE DATE,
        STATTUS VARCHAR(10),
        CUST_ID INT REFERENCES customer (CUST_ID),
        OPEN_BRANCH_ID INT REFERENCES branch (BRANCH_ID),
        OPEN_EMP_ID INT REFERENCES employee (EMP_ID),
        PRODUCT_CD VARCHAR(10) REFERENCES product (PRODUCT_CD)
    );

CREATE TABLE
    business (
        INCORP_DATE DATE,
        NAME VARCHAR(255),
        STATE_ID VARCHAR(10),
        CUST_ID INT REFERENCES customer (CUST_ID)
    );

CREATE TABLE
    customer (
        CUST_ID INT UNIQUE PRIMARY KEY,
        ADDRESS VARCHAR(30),
        CITY VARCHAR(20),
        CUST_TYPE_CD VARCHAR(1),
        FEED_ID VARCHAR(12),
        POSTAL_CODE VARCHAR(10),
        STATE VARCHAR(20)
    );

CREATE TABLE
    individual (
        BIRTH_DATE DATE,
        FIRST_NAME VARCHAR(30),
        LAST_NAME VARCHAR(30),
        CUST_ID INT REFERENCES customer (CUST_ID)
    );

CREATE TABLE
    officer (
        OFFICER_ID INT UNIQUE PRIMARY KEY,
        START_DATE DATE,
        END_DATE DATE,
        FIRST_NAME VARCHAR(30),
        LAST_NAME VARCHAR(30),
        TITLE VARCHAR(20),
        CUST_ID INT REFERENCES customer (CUST_ID)
    );